In [3]:
import numpy as np
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# 1)
x[0][0] = 0; x[0][1] = 0; x[0][2] = 0; x[0][3] = 0
x[1][0] = 0; x[1][1] = 0; x[1][2] = 0; x[1][3] = 0
x[2][0] = 0; x[2][1] = 0; x[2][2] = 0; x[2][3] = 0

# 2)
for i in range(3):
    x[i][0]=0; x[i][1]=0; x[i][2]=0; x[i][3]=0;

# 3)
for i in range(3):
    for j in range(4):
        x[i][j] = 0

x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Numpy 연산

In [16]:
x = [[22,3,4],[4,5,700]] # 2 * 3
np.sum(x)
# np.array(x).sum()

738

In [14]:
type(x)
# Error : AttributeError: 'list' object has no attribute 'sum'
# x.sum() 
# 리스트 형태는 np. 형태로 써줘야지 연산 가능

list

In [ ]:
# 인공신경망(인공지능)은 x값*w값의 합산이 y값과 최대한 차이가 나지않게 하는 w값 찾기

In [38]:
x = np.array([[22,3,4],[4,5,70]])
# [1번사람[x1,x2,x3], 
#  2번사람[x1,x2,x3]] # x1을 몸무게, x2를 나이, x3를 수명량
y = np.array([100, 150]) # 1번 사람 혈압이 100, 2번 사람 혈압이 150일 때
w = np.array([3, 5, 8]) # x1의 w값 3, x2의 w값 5, x3의 w값 8


In [40]:
x*w 
#([22*3,3*5,4*8], [2*3,2*5,3*8])

array([[ 66,  15,  32],
       [ 12,  25, 560]])

In [54]:
y1 = x*w

y_hat=[] # 빈 리스트 만들고 시작하기
for i in y1:
    y_hat.append(i.sum())
y_hat # 예측값

[113, 597]

In [53]:
y_hat - y

array([ 13, 447])

- NA : 값이 기록되지 않았거나 관측되지 않은 경우 데이터에 저장되는 값으로 '결측치'

### 리스트 컴프리헨션(List Comprehension)

In [70]:
y_hat=[]
for i in y1:
    y_hat.append(i.sum())

y_hat

[113, 597]

In [68]:
y_hat = [i.sum() for i in y1]
y_hat

[113, 597]

요약)
- glob와 os.listdir로 폴더 내의 자료를 리스트화 할 수 있음
- numpy 모듈을 이용하여 배열간 연산이 가능
- PIL모듈을 이용하여 이미지 관련 연산이 가능
(배열로 바꾸지 않아도 됨, PIL모듈 기능 중 필요한 기능만 응용할 수 있으면 됨)
- 리스트는 빈 리스트를 만들고 append하는 과정을 압축하여 표현